services:
  - type: web
    name: n8n
    env: docker
    dockerfilePath: ./docker/images/n8n/Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        generateValue: true
      - key: N8N_BASIC_AUTH_PASSWORD
        generateValue: true
      - key: N8N_HOST
        value: https://your-app-name.onrender.com
      - key: WEBHOOK_URL
        value: https://your-app-name.onrender.com
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: DATABASE_TYPE
        value: sqlite
      - key: DATABASE_SQLITE_DATABASE_FILE
        value: /data/database.sqlite
    disk:
      name: n8n-data
      mountPath: /data
      sizeGB: 1
